"""added user_id to participant in case registered user and added author_id to link to author

Revision ID: 323e1ec7ed12
Revises: a31d555f8fd9
Create Date: 2025-05-18 20:10:24.078915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323e1ec7ed12'
down_revision = 'a31d555f8fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key('fk_participant_user_id', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_participant_author_id', 'user', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
