"""Added version to note table

Revision ID: 752697ea1c06
Revises: f0c1593c4c86
Create Date: 2025-03-04 21:02:04.047409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752697ea1c06'
down_revision = 'f0c1593c4c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('version', sa.Integer(), nullable=True, server_default='1'))  # Allow NULL and set default
    op.execute("UPDATE note SET version = 1")  # Set a default for existing rows
    op.alter_column('note', 'version', nullable=False)  # Now enforce NOT NULL

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
