"""added isDeleted and isDeletedTimestamp to Templates

Revision ID: a31d555f8fd9
Revises: c49586632f85
Create Date: 2025-05-16 09:28:43.173541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31d555f8fd9'
down_revision = 'c49586632f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_column('is_deleted_timestamp')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
