"""Added providerId to Note table

Revision ID: f0c1593c4c86
Revises: 7b993462970a
Create Date: 2025-03-04 20:00:06.115267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c1593c4c86'
down_revision = '7b993462970a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('providerId', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('providerName', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('encounterDate', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('noteContentRaw', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('noteContentMarkdown', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('noteType', sa.String(length=50), nullable=False))
        batch_op.alter_column('patientId',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_column('visitType')
        batch_op.drop_column('formattedMarkdown')
        batch_op.drop_column('rawNoteTranscript')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rawNoteTranscript', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('formattedMarkdown', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('visitType', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('patientId',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('noteType')
        batch_op.drop_column('noteContentMarkdown')
        batch_op.drop_column('noteContentRaw')
        batch_op.drop_column('encounterDate')
        batch_op.drop_column('providerName')
        batch_op.drop_column('providerId')

    # ### end Alembic commands ###
